name: Render and Deploy Quarto Book

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Install R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.2'

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
            packages: |
              any::tidyverse
              any::broom
              any::car
              any::effsize
              any::ggpubr
              any::rstatix
              any::gt
              any::patchwork
              any::emmeans
              any::knitr
              any::rmarkdown
              any::here
              any::readxl
              any::writexl
              any::haven
              any::janitor
              any::lubridate
              any::cowplot
              any::glue
              any::kableExtra
              any::effects
              any::effectsize
              any::GGally
              any::ggrepel
              any::MASS
              any::multcomp
              any::multcompView
              any::openxlsx
              any::plotly
              any::pwr
              any::RColorBrewer
              any::scales

      - name: Render Quarto Book
        uses: quarto-dev/quarto-actions/render@v2

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
